### ISSUE TITLE
Cake.Core reference issue

### ISSUE THREAD

**Issue by halex2005** [cake-contrib/Cake.CMake#10]
After releasing [Cake v0.18.0](https://www.nuget.org/packages/Cake/) I got exception while running cake with cake.cmake referenced:

```
Cake.exe : Error: Cake.Core.CakeException: The assembly 'Cake.CMake, Version=0.1.2.0, Culture=neutral, PublicKeyToken=null' is referencing an older version of Cake.Core (0.10.1). This assembly need to reference at least 
Cake.Core version 0.16.0. Another option is to downgrade Cake to an earlier version.
At line:1 char:1
+ & "C:\projects\diadocsdk-cpp\tools\Cake\Cake.exe" "build.cake" -targe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error: Cake.Cor...arlier version.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at Cake.Core.Reflection.AssemblyVerifier.Verify(Assembly assembly)
   at Cake.Core.Reflection.AssemblyLoader.Load(FilePath path, Boolean verify)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
```

**Comment by patriksvensson** [comment]
@halex2005 A new version (0.2.2) has just been pushed to nuget.org: https://www.nuget.org/packages/Cake.Cmake
